config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  minversion: 1.10.3
dotfiles:
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
    link: absolute
  f_gitconfig:
    link: absolute
    src: gitconfig
    dst: ~/.gitconfig
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
    link: absolute
  f_makepkg.conf:
    src: makepkg.conf
    dst: ~/.makepkg.conf
    link: absolute
  f_wgetrc:
    src: wgetrc
    dst: ~/.wgetrc
    link: absolute
  d_zsh:
    src: zsh
    dst: ~/.zsh
    link: absolute
profiles:
  archlinux:
    dotfiles:
    - f_zshenv
    - f_gitconfig
    - f_xprofile
    - f_makepkg.conf
    - f_wgetrc
    - d_zsh
